M48
; DRILL file {KiCad (6.0.4)} date Wed Sep 28 16:49:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-28T16:49:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X3.825Y-2.25
X3.825Y-2.35
X3.825Y-2.45
X4.825Y-2.25
X4.825Y-2.35
X4.825Y-2.45
T0
M30
